################################################
# BattleCraft - BattleBits (KitPvP) Remake 2.0 #
#                                              #
# Editor de Mensagens, Configuracoes, Etc      #
################################################
