name: SloverHG
main: br.com.slovermc.hg.BukkitMain
version: 2.0
commands:
  iniciar:
  tempo:
  kit:
  kit2:
  admin:
  giveitemkit:
  coins:
  fly:
  status:
  forcekit:
  forcekitall:
  score:
  r:
  build:
  specs:
  kitready:
  pickup:
  fake:
  tfake:
  ping:
  ir:
  setip:
  gamemode:
  evento:
  tp:
  minislover:
  finalbattle:
  loja:
  createarena:
  desistir:
  tag:
  cleardrops:
  tphere:
  dano:
  tpall:
  gm:
  pvp:
  togglekit:
  feast:
  forcefeast:
  info:
  invsee:
  skit:
  sc:
  tell:
  prision:
  admin:
  liga:
  ligas:
  ss:
  lobby:
  screenshare:
  xp:
  account:
  addxp:
  removexp:
  chat:
  cc:
  r:
